### ISSUE TITLE
User API - insert and retrieve users

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#1]
The api should speak json and should be appengine admin secured.

Storing a user:
```
location : /v1/users
method : put
data : {
  "role" : (required, enum str : ["hutan_biru", "farmer", ...]),
  "phone_number": (required, str),
  "first_name": (required, str),
  "last_name": (optional, str),
}
```

Retrieving a user:
```
location : /v1/users/<userid>
method : get
response : {
  "id": str,
  "role": (str)
  "phone_number": (str),
  "first_name": (str),
  "last_name": (str, null if not available),
  "ts_created" : (epoch in ms),
  "ts_updated" : (epoch in ms)
}
```

**Comment by Ragil** [comment]
Should also have fetching by phone number. We'll follow a rest interface.
```
location : /v1/users
method : get
request_data: {
  "phone_number" : (optional, str)
}
response : {
  "users": [ (ordered by most recently created)
    { user json - refer to retrieving a user},
    { user json - refer to retrieving a user},
  ]
}
```

**Comment by girikuncoro** [comment]
I still didn't get this yet, is this for storing/retrieving user from/to the datastore?

**Comment by Ragil** [comment]
Storing and retrieving users from the application. We will need to insert the csv we get from hutan biru and we will do it through this api. We don't have direct access to any of the resources that app engine provides so we will need to expose it through our app.

**Comment by girikuncoro** [comment]
My understanding: create two methods, one for writing data to csv, another one for retrieving data from csv, the methods will process the inputted JSON format. Correct?

**Comment by Ragil** [comment]
Nope.

If you look at sms.py, it exposes an endpoint /v1/sms/twilio that can be access via http. The response of that function is a Twiml.

For user management, we will do something similar. We will expose an endpoint /v1/users that be access via http. The response will be json and it is only accessible if you are an admin to the application. We can use http basic authorization for authentication.

**Comment by girikuncoro** [comment]
Oh I think I got it, I'll just need to define the two under `@app.route('/v1/users')` and `@app.route('/v1/users/<userid>')` in `sms.py` then?

**Comment by Ragil** [comment]
Yes but we should put them in user.py and add the entry in app.yaml

**Comment by girikuncoro** [comment]
Got it!

**Comment by Ragil** [comment]
I can do this Thursday if you don't get around to it.

**Comment by girikuncoro** [comment]
#3 is dumb, super simple and straight forward, but let me try to finish this first tonight based on my understanding. You can refactor it Thursday. I still didn't clearly understand the scope of this issue, how to pass/get the data from/to? Would there be another module that we can just use inside the method (like your `twiml.Response()`)? Is it required to validate the params inside the method (like check all required fields, etc.)? Do we also need to generate the epoch ts here (and if new entry put ts in `ts_created`, if not put it in `ts_updated`)?

**Comment by Ragil** [comment]
>  I still didn't clearly understand the scope of this issue, how to pass/get the data from/to?
http://flask.pocoo.org/docs/0.10/quickstart/#accessing-request-data

> Would there be another module that we can just use inside the method (like your twiml.Response())?
http://flask.pocoo.org/docs/0.10/quickstart/#about-responses

You will have to construct the user model that we use to interact with the datastore. This user model would also have a way to convert itself to json. Flask has a built in function to deal with json data.

> s it required to validate the params inside the method (like check all required fields, etc.)?
Yes

> Do we also need to generate the epoch ts here (and if new entry put ts in ts_created, if not put it in ts_updated)?

timestamps should always be generated on the server side. The client should never be trusted.

**Comment by girikuncoro** [comment]
using `db` module like this? https://cloud.google.com/appengine/docs/python/datastore/datamodeling

**Comment by girikuncoro** [comment]
ah I got it, now everything is more make sense, this issue will include the datastore as well.

**Comment by Ragil** [comment]
Yes but use ndb because it adds a lot of nice optimizations and sane caching

https://cloud.google.com/appengine/docs/python/ndb/

**Comment by girikuncoro** [comment]
cool! before this conversation, I was thinking there would be another module that really performs put/get operation to the datastore (outside the scope of this issue), but it's clearer now

**Comment by Ragil** [comment]
how is it going with this?

**Comment by girikuncoro** [comment]
pretty good, give me 20 more minutes to update you

**Comment by Ragil** [comment]
awesome!

**Comment by girikuncoro** [comment]
can you teach me how to navigate the url from `make server`? it always returns 404 at admin server (for both `/v1/sms/twilio` and `/v1/users/something`)

**Comment by girikuncoro** [comment]
I added this in `app.yaml`
```
- url : /v1/users/.*
  script : app.api.user.app
  secure : always
```

**Comment by Ragil** [comment]
curl -v localhost:8080/v1/sms/twilio

**Comment by Ragil** [comment]
curl -v localhost:8080/v1/users/something

**Comment by girikuncoro** [comment]
nice one, I didn't know that we can also do PUT/POST request from `curl` by doing: 
```
curl -H "Content-Type: application/json" X PUT -d '{"role":"farmer", "phone_number": "123123", "first_name": "Giri"}' http://localhost:8080/v1/users
```
I think I'm done, but not with the authentication (did you mean by user admin authentication by admin secured? or just by defining `secure` in `app.yaml` or by only redirecting to admin server (in my case port `8000` not `8080` which is `module default`)

Thanks, I think I learned a lot form this one :smile:

**Comment by girikuncoro** [comment]
and also here I'm assuming the phone numbers are all unique, so I assigned user id with phone numbers. Can I do this?

**Comment by Ragil** [comment]
Ndb should autogenerate a string id for you. You should not use phone number as an ID. Phone numbers are recycle-able (your provider can give your number away to someone else if your not paying for it anymore) and thus not unique.

**Comment by girikuncoro** [comment]
What about this one:
> did you mean by user admin authentication by admin secured? or just by defining secure in app.yaml or by only redirecting to admin server (in my case port 8000 not 8080 which is module default)

**Comment by Ragil** [comment]
Only an admin to the appengine application should be allowed but you can leave that for now. We can probably get away with something simpler. I'll have a think about it.

**Comment by girikuncoro** [comment]
ok I'll make a script test tomorrow and do #3

**Comment by girikuncoro** [comment]
I didn't expect writing test script also takes time. Curl PUT for `/v1/users` works perfectly but not in `test_user.py`. Look at `test_insert` case, any idea why the db doesn't sync when I was trying to HTTP put request? All other test cases are fine (all passed), but I would add more test cases (combining insert/retrieve API) once `test_insert` works perfectly.
https://github.com/Ragil/Communicate-Indonesia/blob/user-ins-rtv/tests/api/test_user.py

This is the app script:
https://github.com/Ragil/Communicate-Indonesia/blob/user-ins-rtv/app/api/user.py

If you have any doc/reference to write up test script for ndb  + put/get request in GAE, that would be awesome.

**Comment by Ragil** [comment]
You are always returning status code 200 even if everything goes well. In fact, the try/catch pattern you are using contributes to this error. Your server should never need a try catch for such a simple scenario. If your server throws an unexpected exception, then you are not guarding against the error cases and should do so.

Secondly, flask uses abort for error responses.
http://flask.pocoo.org/docs/0.10/quickstart/#redirects-and-errors

**Comment by Ragil** [comment]
The api should still return a json response for errors. You can take a look at something I did a long time ago for examples:

https://github.com/Ragil/ragilconfig/blob/master/server/main.py

**Comment by girikuncoro** [comment]
Got it, I should define error handlers in `user.py` then. Great examples, I assume this was the time when Flask `jsonify` didn't exist. Hopefully this can be done tonight.

**Comment by Ragil** [comment]
>  I assume this was the time when Flask jsonify didn't exist.

It existed and it uses jsonify in the decorator. The decorator exist so I didn't have to write return jsonify(data) everywhere. Instead I can simply return data. I wanted to add response code in the return value too. To make something like:

```
# return http 200 with data
return (200, data)

# return http 204 with data
return (204, data)
```

**Comment by Ragil** [comment]
This works fine. I'll make another issue for restricting user api access to admins
