### ISSUE TITLE
Restrict user api request by admin api key

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#10]
We need to add basic authorization to user api that accepts a pre-defined api key for admins

**Comment by girikuncoro** [comment]
1. Can I assume admins have user-password pair stored in db? This means we need new data model for admins?
2. Or do I only need to store pre-defined api key in db, and check if the key is given when user `insert` or `retrieve` (pass the key through POST when insert, and GET when retrieve)?
3. Or is this token based authentication? (Generate token everytime with `app.config` then verify? )
4. Or HTTP basic authentication? (I can simply use `request.authorize` in Flask if my no.1 assumption is correct)
5. This is not OAuth authentication right?

I'll do this tomorrow night, too much fun outside today

**Comment by Ragil** [comment]
> I'll do this tomorrow night, too much fun outside today

#1 priority is always life

> Or do I only need to store pre-defined api key in db, and check if the key is given when user insert or retrieve (pass the key through POST when insert, and GET when retrieve)?

Correct. The api key will be stored in a config object in the db. Every request will read the config from the db and check against it.

> Or HTTP basic authentication? (I can simply use request.authorize in Flask if my no.1 assumption is correct)

The api key will be specified using basic authentication. This would be an example curl:

```
curl -v localhost:8080/v1/users -u "admin:apikey"
```

**Comment by Ragil** [comment]
Since the api key is stored in the db, we will need to use a persistent db for local development. I don't remember the flag for devappserver but it exist and we just need to add the flag in the make server command

**Comment by Ragil** [comment]
The config object is a generic config object that will grow as we add more features. For example, we will need to store the twilio number that we use to send messages

**Comment by girikuncoro** [comment]
By default the devappserver datastore persists, so the data we store will still be available the next time we `make server`, the flag to turn this off is `--clear_datastore=yes`.
https://cloud.google.com/appengine/docs/python/tools/devserver#Python_Using_the_Datastore

Also, in real how are we going to store the API key in the datastore? we don't need API to store this sensitive thing right?
