### ISSUE TITLE
Parse twilio request into SmsRequest domain object

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#11]
Convert the twilio request (https://www.twilio.com/docs/api/twiml/sms/twilio_request) into an SmsRequest that can be passed around to commands and actions.

The SmsRequest should contain:

from_ : the from number
to : the to number
body : the sms body
user : the user associated to the from number if exist

**Comment by Ragil** [comment]
I'll start this off

**Comment by girikuncoro** [comment]
don't forget to spare me some twilio API related issue :smile:

**Comment by Ragil** [comment]
done https://github.com/Ragil/Communicate-Indonesia/pull/24

**Comment by Ragil** [comment]
@girikuncoro  You will need to run "make install" because I added extra dependencies and fixed the pre-commit hook

**Comment by girikuncoro** [comment]
make installed!
