### ISSUE TITLE
Fuzzy matching

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#2]
We need a utility to fuzzy match commands. It should allow for spelling mistakes.

Usage:
```
matcher.match(a, b)
```

Example matches
```
matcher.match("jual", "jual") => true
matcher.match("juall", "jual") => true
matcher.match("juak", "jual") => true
```

**Comment by girikuncoro** [comment]
I'll start with this one since it seems easier, see if I'm fast enough I'll continue with #1 . This will include 5 commands for now: `jual`, `panen`, `tanam`, `lihat`, `kirim`, correct?

**Comment by Ragil** [comment]
It should be independent of language. Ideally the application should be able to support both english and indonesian.

**Comment by Ragil** [comment]
I guess if its easier then we can seed it with all the pre-defined commands.

Something like this should be good enough for us.
http://norvig.com/spell-correct.html

Or we can go even simpler and just use edit distance since our dictionary isn't large.
https://en.wikipedia.org/wiki/Edit_distance

**Comment by girikuncoro** [comment]
You didn't mean independent by literally independent right (includes other than English and Indonesian)? So as of now 5 commands for both English and Indonesian: `jual/sell`, `panen/harvest`, `tanam/plant`, `lihat/look` (or `see`/`read`?), `kirim/broadcast`. Correct? For English I believe the corpus definition exists somewhere

**Comment by Ragil** [comment]
Yeah matching based on edit distance of 1 should be good enough given those words.

**Comment by girikuncoro** [comment]
Cool let's sprint

**Comment by Ragil** [comment]
When I say independent, I'm referring to an approach that isn't as simple as mapping some existing mutations of our commands to the actually commands. eg

```
mapping = {
  "juall" : "jual"
}

match(str, other)
  return str in mapping and mapping[str] == other
```

Using edit distance is independent of the words we are using for commands but it is a good enough solution based on the assumption that our command set is very small.

**Comment by girikuncoro** [comment]
ah yeah before reading the edit distance, I was thinking to define corpus and map like your example but using some probabilistic model. let's use edit distance then.

**Comment by Ragil** [comment]
Also a very simple algorithm to implement :)

**Comment by Ragil** [comment]
wouldn't be surprised if someone has already implemented it and can be included as a dependency

**Comment by girikuncoro** [comment]
it's actually there haha https://pypi.python.org/pypi/editdistance

**Comment by Ragil** [comment]
Cool. We should still scope it to a matcher (or a better named) module so we can swap out the implementation if we need to later.

**Comment by girikuncoro** [comment]
sure

**Comment by Ragil** [comment]
Then onto users api :)

**Comment by girikuncoro** [comment]
hold on dinner first

**Comment by girikuncoro** [comment]
can't we just do:
```
import editdistance as matcher

matcher.eval('juall','jual')
```
this will return the `distance value` (in this case 1), and make a wrapper to return true/false depending on our threshold

**Comment by girikuncoro** [comment]
ah I see what you mean by scoping, I'll wrap out this edit distance in new module

**Comment by girikuncoro** [comment]
I pushed this to branch `command-matcher` yesterday, can we close this issue? or should I merge it first

**Comment by Ragil** [comment]
merge first

**Comment by Ragil** [comment]
then close :)

**Comment by girikuncoro** [comment]
fine to put this under `/app/api/` ?

**Comment by Ragil** [comment]
Probably better in app/util
