### ISSUE TITLE
Implement Sell Action

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#26]
The action should process the sell operation and update appropriate database entries

**Comment by Ragil** [comment]
The behaviour is not entirely correct. It doesn't deal with these test cases https://github.com/Ragil/Communicate-Indonesia/pull/48/files#diff-981dd06e087d5b4db146cf112de02f7eR8

**Comment by girikuncoro** [comment]
Apart from the skipped test cases, is this the only sell behavior has to be fixed?
https://github.com/Ragil/Communicate-Indonesia/blob/master/tests/api/test_sms_api.py#L88-L91

**Comment by girikuncoro** [comment]
What I mean by skipped test cases are here: https://github.com/Ragil/Communicate-Indonesia/blob/master/tests/api/sms/test_sell_action.py I'm implementing this

**Comment by Ragil** [comment]
That was all in terms of sell action that I could think off. It was more of an exercise where thinking about the test before hand could free you to think about all the possible situations rather than writing tests after knowing the implementation.
