### ISSUE TITLE
SSADi18n - Super simple and dumb internationalization module

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#3]
Since we only care about two languages, we can get away with implementing a very simple internationalization module for the application.

It shall live in
```
app/i18n/__init__.py
```

usage:
```
from app.i18n import _

# set the domain based on the user's default language
# we can probably skip this part and default the domain to 'in'
_.domain('in')


type = _('potato') # kentang 
sms = _('{} {} planted') # '{} {} tertanam' 
```

All strings in the application will be in English and passed to i18n. i18n will convert it to Indonesian. Since we only care about two languages, we can simply implement i18n using a map. eg:

```
class i18n(object):
  in = {
    'potato' : 'kentang',
    '{} {} planted' : '{} {} tertanam'
  }

  def __call__(str):
    return self.in[str]
```

**Comment by girikuncoro** [comment]
1. So this thing not only for one word, but should also translate a sentence? 
2. What is your intention by putting curly bracket in '{} {} planted'? there will be another module that will pass words through these?
3. Can I just map each word (one word), and tokenize the input first before looking at the map?
4. I assume the words mapping will be commands and our generic sms response for now
5. If user input other than _.domain('in') what should we return? Here only 'in' is supported and I can just return error for others right?

**Comment by Ragil** [comment]
> So this thing not only for one word, but should also translate a sentence?

No. Its intended to be used for all strings.

> What is your intention by putting curly bracket in '{} {} planted'? there will be another module that will pass words through these?

{} is used for formatting. https://docs.python.org/2/library/stdtypes.html#str.format

> Can I just map each word (one word), and tokenize the input first before looking at the map?
> I assume the words mapping will be commands and our generic sms response for now

We will map every single phrase manually. The module doesn't do anything else but map an English string into the equivalent Indonesian string.

> If user input other than _.domain('in') what should we return? Here only 'in' is supported and I can just return error for others right?

It should return the original string. We will have a test that scrapes all python source code to ensure that every internationalized string has a mapping.

Python has a built-in module for internationalization if you want to over engineer.
