### ISSUE TITLE
Implement query district for amount information

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#38]
```
format : <action> sumatra <filter : sold, plant, harvest>
             lihat sumatra (default quantities/jumlah)

Response SMS (lihat sumatra):
	Hasil Panen Sumatra per 23 Juli 2015
	Singkong 30 kg
	Kentang 10 kg 
```

Responses must be internationalized appropriately.

**Comment by girikuncoro** [comment]
I'll work again on wednesday night, must settle down some stuffs first

**Comment by Ragil** [comment]
Are you in contact with kat?

**Comment by girikuncoro** [comment]
I can contact her, what's up?

**Comment by Ragil** [comment]
I was thinking of looping her on once this issue is done. This should give us something tangible to play with.
