### ISSUE TITLE
Implement broadcast behaviour

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#44]
Broadcast should use task queue to send sms because having to send many sms may take a long time.

https://cloud.google.com/appengine/docs/python/taskqueue/

**Comment by Ragil** [comment]
This might be fun to do since you get to use task queue and also the rest api to send sms.

I'll leave this one for you

**Comment by girikuncoro** [comment]
Any idea what the config for task queue should be in our case? `total_storage_limit`, `rate`, `bucket_size`, etc.
https://github.com/Ragil/Communicate-Indonesia/blob/33421b184e71740ac1efade425bc80a0d82475e5/queue.yaml

**Comment by girikuncoro** [comment]
And the test becomes slow (~5 sec), I don't know if this is fine

**Comment by Ragil** [comment]
The tests are slow because of https://github.com/Ragil/Communicate-Indonesia/pull/46#discussion_r37711548

I simplified and separated a bunch of tests at https://github.com/Ragil/Communicate-Indonesia/pull/48
I've outlined the reasoning in comments. Let me know if you have any questions.

As a by product of testing small, the test also run 50% faster. Its back to around 1s while skipping the broadcast test.

Try reimplementing https://github.com/Ragil/Communicate-Indonesia/issues/26 again and that should give you a better feel of writing small unit tests.

**Comment by girikuncoro** [comment]
This is good exercise for me. Done with reimplementing #26, I'll do this tomorrow/day after tomorrow

**Comment by girikuncoro** [comment]
I believe only the farmers leaders are allowed to broadcast message, any idea how to check this? Can I assume `leader` will be one of the `roles` in User table?

**Comment by Ragil** [comment]
Sure.

I was thinking it might be nicer to rethink we do permissions. Ideally, permissions are a list of possible actions instead of user's role. For example a user can have permission ['record-retrieve-data', 'broadcast-district', 'broadcast-all']

That way seems much nicer instead of having checks for 

```
if role == 'farmer' or role == 'district'
```

**Comment by Ragil** [comment]
It'll be easier to change it now than later. I might change it at some point tonight

**Comment by girikuncoro** [comment]
That might be better and cleaner. We'll need to add permission property in the User data model (and role property might no longer necessary, tho we might need to refactor other methods where user roles are reffered). I will just wait you and continue this tomorrow then.

**Comment by Ragil** [comment]
I agree, changing it tonight.

**Comment by Ragil** [comment]
Thinking about it more leads me to a combined approach. Every action is guarded by a permission and there is a mapping from role to mapping. Roles in this situation acts more like a tag than anything else. Having permission derived from role is so we don't need to expose a complex api for creating users. However, using permission as a guard means we can easily change to update able permission for individual users. In addition, we can also easily bulk change permission for each role since there is a derived component.

**Comment by Ragil** [comment]
Permissions are here : https://github.com/Ragil/Communicate-Indonesia/pull/50/files

**Comment by Ragil** [comment]
Broadcast command throws exceptions. I've temporarily turned it off here https://github.com/Ragil/Communicate-Indonesia/pull/52/files#diff-0c33c381dbe0331c33521416bccaa79aR32

**Comment by girikuncoro** [comment]
Merged in #59 and commented https://github.com/Ragil/Communicate-Indonesia/commit/d51f8099b0e30761b4295c342f8a8164c1b6fd56#commitcomment-12964078

**Comment by Ragil** [comment]
https://github.com/Ragil/Communicate-Indonesia/pull/61
