### ISSUE TITLE
We need better error message when a command is not matched.

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#54]
Currently we only say "Unknown Command". We should probably also return what commands we can accept.

**Comment by girikuncoro** [comment]
In our current app, `Unknown Command` will be sent not only for command other than `PLANT`, `HARVEST`, `SELL`, and `BROADCAST`, but also valid command with invalid formatting (i.e. `PLANT` without specifying any amount and crops name)

**Comment by girikuncoro** [comment]
The new sms response might be confusing though, if we take example from telco carriers in Indonesia (e.g. Telkomsel), as a user when we want to register some features through SMS command (i.e. REG SOMETHING) and the command is invalid, their response is only `ABC command is invalid, try again`

**Comment by Ragil** [comment]
Lets try this format and see what feedback we get.
