### ISSUE TITLE
SMS API - implement command parsing framework

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#6]
We to abstract incoming sms messages from Twilio and implement command parsing and dispatching framework.

**Comment by Ragil** [comment]
I'll work on this one

**Comment by girikuncoro** [comment]
are you done with this?

**Comment by Ragil** [comment]
Nope

**Comment by Ragil** [comment]
Done https://github.com/Ragil/Communicate-Indonesia/pull/9

There is an example PlantCommand to illustrate the pattern. The PlantAction doesn't currently do anything.
