### ISSUE TITLE
Add units to plants

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#66]
We need to:

1. design how its going to be stored
2. Identify and implement all the changes required for each command.
3. clear out any existing data in staging environment and repopulate with appropriate user data to enable usage from the team.

**Comment by girikuncoro** [comment]
Initially `Farm` data model is as below:
```
data : {
  "district_id" : (required, str),
  "action" : (required, enum str : ["harvest", "plant", "sell"]),
  "crop_name" : (required, str),
  "quantity" : (required, int)
}
```
Units and `register` command are going to impact `Farm` data model. Unit has 3 categories: weight (kg, g, ..), volume (liter, ml, ..), and count. Each category can only be converted within the same category. Thus, we need to add:
```
data : {
  "unit_type" : (required, enum str : ["weight", "volume", "count"])
}
```
Depending on the unit type, we stored the crops in "standard" unit for each category.
Standard unit for:
-weight: kg
-volume: liter
-count: None

So, if users update crop that is associated with weight unit type, input crop with "g" unit will be converted automatically to "kg" in the datastore.

**Comment by Ragil** [comment]
sounds good.

**Comment by Ragil** [comment]
We can close this and move forward with the design.
